### ISSUE TITLE
Orderbooks shouldn't be compared twice in the same pair check

### ISSUE THREAD

**Issue by andygoossens** [cryptoeax/arbbot#118]
I think that commit 27ef12c introduced an inefficiency.

We have:
```
      if ( $this->checkPairAt( $pair, $x1, $x2 ) ||
           $this->checkPairAt( $pair, $x2, $x1 ) ) {
```
and a bit further
```
return ( $this->checkAndTrade( $o1, $o2 ) ) || $this->checkAndTrade( $o2, $o1 );
```

When "Checking $pair @ $exchangeA -> $exchangeB" we will:
* fetch order books at $exchangeA
* fetch order books at $exchangeB
* investigate whether it's worth to trade from $exchangeA to $exchangeB
* investigate whether it's worth to trade from $exchangeB to $exchangeA

Afterwards we do the reverse: "Checking $pair @ $exchangeB -> $exchangeA":
* fetch order books at $exchangeB
* fetch order books at $exchangeA
* investigate whether it's worth to trade from $exchangeB to $exchangeA
* investigate whether it's worth to trade from $exchangeA to $exchangeB

But we have already done these investigations just seconds earlier. Isn't it better to wait until the next loop?

I noticed this because I received "Sell order not fullfilled, we will not attempt a buy order to avoid incurring a loss." twice in a few seconds for the same pair with the same source and the same target exchange.

**Comment by cryptoeax** [comment]
Hmm, yes, you are completely right.

The actual assymetry that I meant to leverage in that commit (and failed to do so) was this one:

https://github.com/cryptoeax/arbbot/blob/d8bfc701e986760a9655e6f383f3fd6050f83537/bot/Arbitrator.php#L102

Basically the transfer restrictions on which pairs to pick should only affect the exchange on the buy side (since we only transfer out of that exchange.)  But this means that we need to flip the order of the exchange arguments *here*:

https://github.com/cryptoeax/arbbot/blob/d8bfc701e986760a9655e6f383f3fd6050f83537/bot/Arbitrator.php#L91

Thanks a lot for spotting this mistake!

**Comment by cryptoeax** [comment]
I think with ccae898 this should now be working as intended.  Please let me know if it's not!

**Comment by andygoossens** [comment]
The issue remains:
```
14:35:26: Checking BLEUTRADE vs HITBTC (1 common pairs)
14:35:26: Checking 1 random pairs...
14:35:26: Checking DOGE_BTC at BLEUTRADE -> HITBTC...
14:35:27: SPREAD : 0.00000001 BTC = 0.00019693 BTC PROFIT
14:35:27: [DB] Omitting track 38250.43383385 DOGE @ HITBTC as previous entry is too young
14:35:27: Testing if trading is profitable with available funds...
14:35:27: TRADING DOGE-BTC FROM BLEUTRADE TO HITBTC
...snip...
14:35:45: Sell order not fullfilled, we will not attempt a buy order to avoid incurring a loss.
14:35:46: Checking HITBTC vs BLEUTRADE (1 common pairs)
14:35:46: Checking 1 random pairs...
14:35:46: Checking DOGE_BTC at HITBTC -> BLEUTRADE...
14:35:47: SPREAD : 0.00000001 BTC = 0.00019693 BTC PROFIT
14:35:47: [DB] Omitting track 38250.43383385 DOGE @ HITBTC as previous entry is too young
14:35:47: Testing if trading is profitable with available funds...
14:35:47: TRADING DOGE-BTC FROM BLEUTRADE TO HITBTC
```

Notice that "TRADING DOGE-BTC FROM BLEUTRADE TO HITBTC" is happening twice in the same loop.

I am guessing that we need to drop `$this->checkAndTrade( $o2, $o1 )` from the testOrderbooks() function as well.

**Comment by cryptoeax** [comment]
Hrm, right.  So in this case you have *one* common pair...  Which causes the repetition to happen (and that's obviously guaranteed!)

But in case where there are many common pairs which is what I was looking at before, the algorithm now picks up random pairs in the reverse direction again so there is a chance that it will pick different pairs.  That's why I didn't see the issue is still there...

Your suggestion seems to work pretty well.  We could do something more sophisticated but given that we'll get to any pair/exchange left unchecked in future loop iterations it should be alright I think.
